version: 2.1
jobs:
  ensure-deps:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v4-yarn-{{ .Branch }}-
            - v4-yarn-
      - run:
          name: Setup Registry Access
          command: echo "registry=https://registry.npmjs.org/" > ~/.npmrc && echo "@eMarketeerSE:registry=https://npm.pkg.github.com/" > ~/.npmrc && echo "//npm.pkg.github.com/:_authToken=${NPM_REGISTRY_TOKEN}" >> ~/.npmrc

      - run:
          name: Install Dependencies
          command: yarn --production=false


      - save_cache:
          key: v4-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .cache/yarn
  checks:
    environment:
      PROJECT: node-spf-check
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: build/distributions
      - restore_cache:
          keys:
            - v4-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v4-yarn-{{ .Branch }}-
            - v4-yarn-
      - run:
          name: create folder
          command: mkdir -p reports/junit
      - run:
          name: Unit tests
          command: yarn test
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit



workflows:
  version: 2
  build-and-test:
    jobs:
      - ensure-deps:
          context: dev-emarketeer
      - checks:
          requires:
            - ensure-deps
